language: php
os: linux
dist: xenial

jobs:
  allow_failures:
    - php: 7.4
  include:
    - php: 7.3
      env: 'COMPOSER_FLAGS="--prefer-stable"'
    - php: 7.3
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.4
      env: 'COMPOSER_FLAGS="--prefer-stable"'
    - php: 7.4
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

services:
  - mysql
  - docker

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - travis_retry php artisan key:generate
  - travis_retry php artisan migrate
  - . $HOME/.nvm/nvm.sh
  - nvm install 13.12.0
  - nvm use 13.12.0
  - npm install -g yarn
  - yarn
  - yarn run production

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

script:
  - vendor/bin/phpunit --debug
  - docker-compose build
