
version: '2'
services:
  redis:
    image: redis
    restart: always
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /srv/pgr-test/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr-test:
    image: lcasuol/pgr_system:pgr-test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE
        - SOURCE_COMMIT
        - VERSION      
    restart: always
    #build: . 
    command: "bash -c 'if [ -r /srv/config/.htaccess ]; then ln -fsv /srv/config/.htaccess /var/www/html/pgr/public/.htaccess; fi && ln -fsv /srv/config/.env /var/www/html/pgr/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
      - redis
      - smtp
    ports:
      - 8081:443
    volumes:
      - /srv/pgr-test/storage:/var/www/html/pgr/storage
      - /srv/pgr-test/config:/srv/config

  smtp:
    image: djfarrelly/maildev
    command: "bin/maildev --web 80 --smtp 25 --outgoing-host mailslot.lincoln.ac.uk --outgoing-port 25 --base-pathname /maildev"
    volumes:
      - /srv/maildev/storage-test:/tmp/maildev
    ports:
      - "8091:80"
      - "1125:25"
